public static void Create_Metro_Map(Graph_M g)
		{
			g.addVertex("WASHERMENPET METRO~R");
			g.addVertex("MANNADI~R");
			g.addVertex("HIGH COURT~R");
			g.addVertex("CENTRAL METRO~RB");
			g.addVertex("EGMORE METRO~B");
			g.addVertex("NEHRU PARK~B");
			g.addVertex("KILPAUK~B");
			g.addVertex("PACHAIYAPPAS COLLEGE~B");
			g.addVertex("SHENOY NAGAR~B");
			g.addVertex("ANNA NAGAR EAST~B");
			g.addVertex("ANNA NAGAR TOWER~B");
			g.addVertex("THIRUMANGALAM~B");
			g.addVertex("KOYAMBEDU~B");
			g.addVertex("CMBT~B");
			g.addVertex("ARUMBAKKAM~B");
			g.addVertex("VADAPALANI~B");
			g.addVertex("ASHOK NAGAR~B");
			g.addVertex("EKKATTUTHANGAL~B");
			g.addVertex("ALANDUR~RB");
			g.addVertex("ST.THOMAS MOUNT METRO~B");
            g.addVertex("GOVERNMENT ESTATE~R");
            g.addVertex("LIC~R");
            g.addVertex("THOUSAND LIGHTS~R");
            g.addVertex("AG-DMS~R");
            g.addVertex("TEYNAMPET~R");
            g.addVertex("NANDANAM~R");
            g.addVertex("SAIDAPET METRO~R");
            g.addVertex("LITTLE MOUNT~R");
            g.addVertex("GUINDY METRO~R");
            g.addVertex("NANGANALLUR ROAD~R");
            g.addVertex("MEENAMBAKKAM METRO~R");
            g.addVertex("AIRPORT~R");
			
			g.addEdge("WASHERMENPET METRO~R", "MANNADI~R", 10);
			g.addEdge("MANNADI~R", "HIGH COURT~R", 10);
			g.addEdge("HIGH COURT~R", "CENTRAL METRO~RB", 10);
			g.addEdge("CENTRAL METRO~RB", "EGMORE METRO~B", 10);
			g.addEdge("CENTRAL METRO~RB", "GOVERNMENT ESTATE~R", 10);
			g.addEdge("GOVERNMENT ESTATE~R", "LIC~R", 10);
			g.addEdge("LIC~R", "THOUSAND LIGHTS~R", 10);
			g.addEdge("THOUSAND LIGHTS~R", "AG-DMS~R", 10);
			g.addEdge("AG-DMS~R", "TEYNAMPET~R", 10);
			g.addEdge("TEYNAMPET~R", "NANDANAM~R", 10);
			g.addEdge("NANDANAM~R", "SAIDAPET METRO~R", 10);
			g.addEdge("SAIDAPET METRO~R", "LITTLE MOUNT~R", 10);
			g.addEdge("LITTLE MOUNT~R", "GUINDY METRO~R", 10);
			g.addEdge("GUINDY METRO~R", "ALANDUR~RB", 10);
			g.addEdge("ALANDUR~RB", "NANGANALLUR ROAD~R", 10);
			g.addEdge("NANGANALLUR ROAD~R", "MEENAMBAKKAM METRO~R", 10);
			g.addEdge("MEENAMBAKKAM METRO~R", "AIRPORT~R", 10);
			g.addEdge("EGMORE METRO~B", "NEHRU PARK~B", 10);
			g.addEdge("NEHRU PARK~B", "KILPAUK~B", 10);
            g.addEdge("KILPAUK~B", "PACHAIYAPPAS COLLEGE~B", 10);
            g.addEdge("PACHAIYAPPAS COLLEGE~B", "SHENOY NAGAR~B", 10);
            g.addEdge("SHENOY NAGAR~B", "ANNA NAGAR EAST~B", 10);
            g.addEdge("ANNA NAGAR EAST~B", "ANNA NAGAR TOWER~B", 10);
            g.addEdge("ANNA NAGAR TOWER~B", "THIRUMANGALAM~B", 10);
            g.addEdge("THIRUMANGALAM~B", "KOYAMBEDU~B", 10);
            g.addEdge("KOYAMBEDU~B", "CMBT~B", 10);
            g.addEdge("CMBT~B","ARUMBAKKAM~B", 10);
            g.addEdge("ARUMBAKKAM~B", "VADAPALANI~B", 10);
            g.addEdge("VADAPALANI~B", "ASHOK NAGAR~B", 10);
            g.addEdge("ASHOK NAGAR~B", "EKKATTUTHANGAL~B", 10);
            g.addEdge("EKKATTUTHANGAL~B", "ALANDUR~RB", 10);
            g.addEdge("ALANDUR~RB", "ST.THOMAS MOUNT METRO~B", 10);
}
